### ISSUE TITLE
type object 'Quaternion' has no attribute 'distance'

### ISSUE THREAD

**Issue by bayantaani** [KieranWynn/pyquaternion#12]
I am implementing a project that requires me to use  the distance and slerp functions on a set of quaternion data which I have in a file.

Whenever I call the method Quaternion.distance(q0, q1), I get the following error:
"AttributeError: type object 'Quaternion' has no attribute 'distance'"
The same happens for the remaining distance methods (absolute_distance, sym_distance) and the log methods.

How can I fix this?

**Comment by KieranWynn** [comment]
Hi bayantaani

The distance functions are a newly added feature. They are still in testing and have not been released to PyPi yet. Stay tuned for an updated version there soon.

If you need the features now, please clone and install pyquaternion yourself into your local environment:
`pip install <path to pyquaternion setup.py>`

**Comment by bayantaani** [comment]
Thank you KieranWynn for the prompt reply!
I did as you suggested, I get the following error for the distance method:

`>>> dist = Quaternion.distance(q0,q1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyquaternion/quaternion.py", line 798, in distance
    q = Quaternion.log_map(q0, q1)
  File "pyquaternion/quaternion.py", line 729, in log_map
    return Quaternion.log(q.inverse * p)
AttributeError: 'function' object has no attribute 'inverse`

When I call inverse alone I get the same error as above; that it doesn't exist.

And this for absolute_distance:

`>>> dist = Quaternion.absolute_distance(q0,q1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyquaternion/quaternion.py", line 770, in absolute_distance
    q0_minus_q1 = q0 - q1
TypeError: unsupported operand type(s) for -: 'instancemethod' and 'instancemethod'`

am I missing something?

**Comment by KieranWynn** [comment]
Hi @bayantaani 
It looks like you are passing a python function object or instance method to these functions rather than a Quaternion object. Your error is likely in your declaration of `q0` and `q1`. I'm guessing you are doing something like `q0 = Quaternion.random` rather than `q0 = Quaternion.random()`. Does that fix it for you?

**Comment by bayantaani** [comment]
Oh I did not pay attention to that!! Thank you
