### ISSUE TITLE
Minor bug in documentation regarding chaining

### ISSUE THREAD

**Issue by pewscorner** [KieranWynn/pyquaternion#15]
Under "Basic Usage" it says that q1 * q2 is a quaternion that rotates by q1 then q2, but I believe it is q2 then q1 (the multiplied quaternions are applied in reverse order).

**Comment by KieranWynn** [comment]
Thanks @pewscorner you are correct.
This has also been reported in https://github.com/KieranWynn/pyquaternion/issues/27 and fixed in https://github.com/KieranWynn/pyquaternion/pull/49
