### ISSUE TITLE
AttributeError: 'Quaternion' object has no attribute 'rotation_matrix'

### ISSUE THREAD

**Issue by HyuanTan** [KieranWynn/pyquaternion#17]
@KieranWynn Hi, thanks for share!
When I use `quaternion.rotation_matrix `, I got some error like `AttributeError: 'Quaternion' object has no attribute 'rotation_matrix'`.
The codes I use pyquaternion are:
`       quaternion = Quaternion(w=orientation.w, x=orientation.x, y=orientation.y, z=orientation.z)
        R = quaternion.rotation_matrix       # 3x3 rotation matrix
        T = quaternion.transformation_matrix  # 4x4 transformation matrix`

Can you help me figure out what's wrong when I used these codes?
Thanks!

**Comment by KieranWynn** [comment]
Hi @HyuanTan
I can't reproduce this using a fresh install from pip.
This is what I get:
```
>>> from pyquaternion import Quaternion
>>> orientation = [1, 0, 0, 0]
>>> quaternion = Quaternion(w=orientation[0], x=orientation[1], y=orientation[2], z=orientation[3])
>>> R = quaternion.rotation_matrix
>>> T = quaternion.transformation_matrix
>>> R
array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])
>>> T
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
>>>
```

**Comment by HyuanTan** [comment]
@KieranWynn Thanks! Maybe I passed the  invalid  value to `quaternion = Quaternion(w=orientation.w, x=orientation.x, y=orientation.y, z=orientation.z)` and caused that error. It work now!
Thanks!!
