### ISSUE TITLE
Easy access to quaternion elements

### ISSUE THREAD

**Issue by varunagrawal** [KieranWynn/pyquaternion#22]
Hey. Thanks for the fantastic work on this library.

I was wondering if it would be good to add properties to access the quaternion elements directly, i.e. instead of doing `q.real` and `q.vector[0]`, `q.vector[1]` & `q.vector[0]`, a user could simply do `q.w`, `q.x`, `q.y` & `q.z`?
This would be 100% backwards compatible since we are only adding new instance properties, but these should make testing and debugging much easier and more readable.

I'd be happy to submit a PR for this.

**Comment by rpapallas** [comment]
This looks like is already there? (https://github.com/KieranWynn/pyquaternion/pull/23/commits)

**Comment by rpapallas** [comment]
This looks like is now resolved: https://github.com/KieranWynn/pyquaternion/pull/23
