### ISSUE TITLE
Bug in Slerp Interpolation

### ISSUE THREAD

**Issue by nileshkulkarni** [KieranWynn/pyquaternion#24]
Hi, 
I have observed a bug in the slerp interpolation offered by pyquaternion. Following is my test case to show case the same. I compared it against Matlab's implementation, the answer from matlab appears to be correct. 

Python

![image](https://user-images.githubusercontent.com/2604793/44685136-b48ee200-aa18-11e8-85f3-d30ebb55573c.png)

Matlab
![image](https://user-images.githubusercontent.com/2604793/44685183-dd16dc00-aa18-11e8-8495-3977f669711e.png)

The answers from Matlab and pyquaternion do not match.

**Comment by oscar-nutonomy** [comment]
I have observed a related error. Consider this code:
```
from pyquaternion import Quaternion
import numpy as np
a = Quaternion([0.011633975364000317, 0.008876065842186651, 0.0019237071183384146, -0.9998910767795249])
b = Quaternion([0.001300462311085926, -0.009003606569652578, -0.0009234925077518404, 0.9999581946402082])
c = Quaternion.slerp(a, b, 0.5)

print("a-b\n", a.rotation_matrix - b.rotation_matrix)
print("b-c\n", b.rotation_matrix - c.rotation_matrix)
print("a-c\n", a.rotation_matrix - c.rotation_matrix)
```
The output is:
```
a-b
 [[ 2.62755588e-04  2.58837526e-02  3.03424933e-04]
 [-2.58487118e-02  2.73011982e-04 -2.23003293e-03]
 [ 2.09099619e-04 -1.77014180e-03 -1.13484848e-06]]
b-c
 [[-1.98789379  0.00924679 -0.17162799]
 [-0.00618198 -1.9997481  -0.02222262]
 [ 0.1358185   0.01693347  0.01191661]]
a-c
 [[-1.98763104  0.03513054 -0.17132457]
 [-0.03203069 -1.99947509 -0.02445265]
 [ 0.1360276   0.01516332  0.01191548]]
```
So the quaternions a & b encode the same angle more or less. But the interpolated angle is vastly different. It appears the slerp is not actually finding the shortest path. 

OTW: thank for a fantastic library!

**Comment by oscar-nutonomy** [comment]
I found a work-around using the (otherwisee dreadful) geotransforms.py. The quaternion_slerp method there works. 
https://github.com/nutonomy/nuDeep/blob/8d94f4bd67966cefc12681d272331553fe339072/nupylib/utils/geo_transforms.py#L1431

**Comment by KieranWynn** [comment]
Thanks for the detailed reporting folks. I'll have a look into this asap.

**Comment by oscar-nutonomy** [comment]
> Thanks for the detailed reporting folks. I'll have a look into this asap.

no probs. I just realized I gave you a bad url. Check out `quaternion_slerp` here: https://www.lfd.uci.edu/~gohlke/code/transformations.py.html

**Comment by cosama** [comment]
Looked through some code on this. Here they added an additional if:

https://github.com/moble/quaternion/blob/64828eb3231ab48a423ea3301f5c8678af646bdb/quaternion.h#L466

Maybe that helps.

**Comment by oscar-nutonomy** [comment]
@KieranWynn : did you get a chance to look at this?

**Comment by cosama** [comment]
I ended up using an implementation based on the example provided in https://en.wikipedia.org/wiki/Slerp. Haven't tested it extensively but seems to work so far.

**Comment by oscar-nutonomy** [comment]
@cosama : would you be willing to make a PR to this repo so we can all try it out?

**Comment by cosama** [comment]
I put in a PR for this now. Have a look and let me know if it still causes issues. If it is tested sufficiently it probably can be merged.

**Comment by oscar-nutonomy** [comment]
@cosama @KieranWynn : I teated the PR on my data and it all looks good. Tricky to write extensive unit-tests thought.

**Comment by cosama** [comment]
@oscar-nutonomy I wrote some for another library, doing some simple slerp around a fixed axis and check if the rotation angle is correct. I will add it tomorrow, if I don't forget.
