### ISSUE TITLE
Bug in Quaternion Interpolation

### ISSUE THREAD

**Issue by ouyangal** [KieranWynn/pyquaternion#25]
Hi,

I have observed a bug in Quaternion.Intermediates function. I originally had the setting to have 4 interpolated values, when I observed the following:
<img width="255" alt="screen shot 2018-09-12 at 2 47 34 pm" src="https://user-images.githubusercontent.com/5032087/45446610-5ceca980-b69b-11e8-9641-acd6ff7491b9.png">

In the animation based of the demo, I also observed jerky movement in the figure, whereas the recording of the object that I had collected the quaternion measurements from, had no such movement.

Even with 1 interpolated value, this extremity is calculated:
<img width="259" alt="screen shot 2018-09-12 at 2 49 49 pm" src="https://user-images.githubusercontent.com/5032087/45446708-958c8300-b69b-11e8-9d9f-03e9713e74c7.png">
It seems very unreasonable for the w quaternion value to go from 0.002 to 0.839 and then back to 0.006.

Without any interpolation, this are the values in my data, which have no unexplainable change in the quaternion numbers, although the animation is jerky without the interpolation:
<img width="249" alt="screen shot 2018-09-12 at 2 48 23 pm" src="https://user-images.githubusercontent.com/5032087/45446848-ebf9c180-b69b-11e8-89b9-7b055e8dba21.png">

**Comment by oscar-nutonomy** [comment]
I'm guessing this is fixed in https://github.com/KieranWynn/pyquaternion/pull/31. Can you check @ouyangal ?

**Comment by KieranWynn** [comment]
Hi @ouyangal 
Thanks for picking this up. That does seem like a glitch in the interpolation functionality.

I've just merged https://github.com/KieranWynn/pyquaternion/pull/31 which should address this issue. Can you let me know if you're still seeing this behaviour using the latest build (0.9.5)?
