### ISSUE TITLE
Reference frame not documented

### ISSUE THREAD

**Issue by sblinz** [KieranWynn/pyquaternion#27]
It would be very helpful if the reference frame for your Quaternions was documented. I assumed that it would be the "traditional" right-handed right-forward-up / east-north-up. But, when I looked at the Basic Usage example with `v = [0, 0, 1],  q1 = Quaternion(axis=[1, 0, 0], angle=3.14159265), q2 = Quaternion(axis=[0, 1, 0], angle=3.14159265 / 2)` I expected to get _negative_ x-axis [-1, 0, 0] for the result of `(q1*q2).rotate(v)` but the documentation/output is `[1, 0, 0]`.

Perhaps I am making a mistake about quaternion composition and handedness. In any case, it would be helpful to document the reference frame.

Thank you for making this!

**Comment by bc** [comment]
is this package a left handed coordinate system?

where

right is +x
up is +y
forward is +z

**Comment by KieranWynn** [comment]
Thanks for the feedback and apologies for the confusion - pyquaternion assumes a right-handed coordinate system.
It turns out the documentation for composite rotations has the multiplication in the wrong order. It should read:
```
>>> q1 = Quaternion(axis=[1, 0, 0], angle=3.14159265) # Rotate 180 about X
>>> q2 = Quaternion(axis=[0, 1, 0], angle=3.14159265 / 2) # Rotate 90 about Y
>>> q3 = q2 * q1  # Composite rotation of q1 then q2 expressed as standard multiplication (note quaternions are multiplied in reverse order of rotation)
>>> v_prime = q3.rotate(v)
>>> v_prime
array([ -1., 0., 0.])
>>>
```

I will update the published docs to clarify.
