### ISSUE TITLE
change of basis two 3D coordinate systems Quaternion

### ISSUE THREAD

**Issue by rfsch** [KieranWynn/pyquaternion#41]
Hello 

I have a point cloud in the coordinate system of a LIDAR sensor and a frenet-serret coordinate system defined by three orthogonal uniot vectors in the cartesian system. I want transpose the pointcloud's points into the frenet-serret coordinates. 

Can  you please give me a hint how I can do it with pyquaternion ? 

Thanks

**Comment by KieranWynn** [comment]
Hi rfsch
pyquaternion will allow you to perform arbitrary vector rotations within any cartesian reference frame. It leaves it up to you to build transformation between frames.
May I suggest reading more generally on how to map between a frenet-serret coordinate system and a static one.

I'm going to close this as a general question not directly related to pyquaternion.
