### ISSUE TITLE
Error in the __float__ method

### ISSUE THREAD

**Issue by Hojjatrt** [KieranWynn/pyquaternion#42]
hey, guys in the float method we have an error:

DeprecationWarning: Quaternion.__float__ returned non-float (type numpy.float64).  The ability to return an instance of a strict subclass of float is deprecated, and may be removed in a future version of Python.
  print(float(dq.real))

I can pull this to the master

**Comment by KieranWynn** [comment]
Resolved by https://github.com/KieranWynn/pyquaternion/pull/43
