### ISSUE TITLE
How to initialize Quaternion from yaw, pitch, roll?

### ISSUE THREAD

**Issue by witwitchayakarn** [KieranWynn/pyquaternion#51]
Hi,

Suppose that I get yaw, pitch, roll from method 'yaw_pitch_roll' then I change some values of them. How can I get/initialize a Quaternion object from my updated yaw, pitch, roll?

Please help. Thank you so much.

**Comment by witwitchayakarn** [comment]
I ended up using this https://www.andre-gaschler.com/rotationconverter/ to get Quaternion's elements from yaw, pitch, roll.

Thank you.

**Comment by bjajoh** [comment]
It's actually really simple, here the solution for all the future people having the same issue:
`Quaternion(axis=[0, 0, 1], angle=3.14159265)`
Note: the angle is in radians. This example initializes a yaw angle of 180°

**Comment by zhangpur** [comment]
Hi, @bjajoh, is the rotation clockwise or counter-clockwise? I mean the positive direction of the angle. Thanks.

**Comment by bjajoh** [comment]
@zhangpur Sorry I forgot that, just try it and maybe comment for future people asking the same :)
