### ISSUE TITLE
Permission to submit PEP484 stubs to Typeshed

### ISSUE THREAD

**Issue by trickeydan** [KieranWynn/pyquaternion#54]
Hi,

I am requesting permission from the authors of this project to write and submit PEP 484 type stubs for this project to [typeshed](https://github.com/python/typeshed).

This will allow users of static type checkers such as `mypy` and `pycheck` to typecheck their use of `pyquaternion`. As this module supports versions of Python < 3.5, it is unfortunately not possible to include them as inline stubs.

The maintainers of typeshed require that I obtain consent from the maintainers of this project before submitting to them:

```
NOTE: When you're contributing a new stub for a package that you did not develop, please obtain consent of the package owner (this is specified in PEP 484). The best way to obtain consent is to file an issue in the third-party package's tracker and include the link to a positive response in your PR for typeshed.
```

Thanks,

Dan

**Comment by KieranWynn** [comment]
Hi Dan

Thanks for checking in. 
This is an idea that I fully support and endorse. Please go ahead.

FYI I will be aiming to drop support for python < 3.5 in the next major version of pyquaternion, so I'll be adding inline typing as part of that.
