### ISSUE TITLE
We have Python type stub file (*.pyi) for Pyquaternion

### ISSUE THREAD

**Issue by polalab** [KieranWynn/pyquaternion#58]
Hi,
To be able to run type checks on our code using Pyquaternion, we have created a pyi file for pyquaternion. This allows mypy to check if we are using it correctly (and makes IDEs like PyCharm autocomplete methods for Quaternion objects). Do you want to include it in your package?

The file is attached, so that you can have a look:
[quaternion.zip](https://github.com/KieranWynn/pyquaternion/files/4581051/quaternion.zip)

**Comment by KieranWynn** [comment]
Thank you @polalab 
Hoping to add types in 1.0 release - this will be handy as a starting point.
