### ISSUE TITLE
Quaternion exponents appear to be broken with python 3.6.2 and numpy 1.12.1

### ISSUE THREAD

**Issue by JonasT** [KieranWynn/pyquaternion#6]
It appears that quaternion exponents are broken for me for some reason:

```
Python 3.6.2 (default, Jul 19 2017, 13:09:21) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyquaternion
>>> q = pyquaternion.Quaternion(axis=[1.0, 0, 0], angle=0.0)
>>> q ** 0.5
/home/jonas/Develop/simplehorror/pyquaternion/quaternion.py:420: RuntimeWarning: invalid value encountered in true_divide
  n = self.vector / np.linalg.norm(self.vector)
Quaternion(nan, nan, nan, nan)
>>> 
```

**Comment by JonasT** [comment]
After more investigation, the problem is that the quaternion's `.vector` member is only zeroes. After changing this manually, there is no longer an error:
```
jonas@cyberman:~/Develop/simplehorror$ python3
Python 3.6.2 (default, Jul 19 2017, 13:09:21) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyquaternion
>>> q  = pyquaternion.Quaternion(axis=[1.0, 0, 0], angle=0.0)
>>> q.vector
array([ 0.,  0.,  0.])
>>> q.vector[0] = 1
>>> q *= 0.5
>>>
```
Now given what I entered should be a valid quaternion, I guess the internal vector resulting from that shouldn't be just zeroes?

**Comment by KieranWynn** [comment]
So the current implementation for powers of quaternions uses [this](https://en.wikipedia.org/wiki/Quaternion#Exponential.2C_logarithm.2C_and_power). When the vector component is has no length, this operation is ill defined and results in what is essentially a ZeroDivisionError. Will look into this and see if there is a logical result in this special case.

**Comment by JonasT** [comment]
Ah so I guess it's because the quaternion represents the identity transformation rotation? (Since the axis itself clearly has a proper length, so it is a valid quaternion for sure.) In that case, IMHO the result should just be the identity rotation again.

**Comment by KieranWynn** [comment]
Fixed in PR `Issue6 exponents broken for real numbers`
