### ISSUE TITLE
Quaternion constructor is broken (at least for some values of axis=)

### ISSUE THREAD

**Issue by JonasT** [KieranWynn/pyquaternion#8]
In the latest revision https://github.com/KieranWynn/pyquaternion/commit/b30857a7389c69156eccf70de2a48742338f1e60 which fixes real number exponents, the constructor for Quaternions seems to be broken when constructing them from an axis + angle:
```shell
jonas@cyberman:~/Develop/simplehorror$ python3
Python 3.6.2 (default, Jul 19 2017, 13:09:21) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyquaternion import Quaternion
>>> q = Quaternion(axis=[0.0, 1.0, 0.0], angle=0.0)
>>> q.axis
array([ 0.,  0.,  0.])
>>>
```

**Comment by KieranWynn** [comment]
This is the intended and documented behaviour. http://kieranwynn.github.io/pyquaternion/#accessing-rotation-axis

The rotation axis of a null rotation has an infinite number of possibilities. I have chosen [0, 0, 0] by convention. If you want specific behaviour in this case, please use `Quaternion.get_axis()` and specify the optional `undefined` argument as a vector to be returned in the case of a null rotation.

**Comment by JonasT** [comment]
@KieranWynn isn't any axis not [1, 0, 0] basically a non-null rotation? Or is the axis not the same as the x,y,z real number members?

**Comment by JonasT** [comment]
I am bit confused because I tried something which I assumed was very basic.
I'm converting the in-engine Quaternion I have to pyquaterion, apply `**` for a partial rotation and then just convert it back. But it seems I'm just getting nonsense as a result:
```python3
def partial_rotation(rotation, progress):
    if progress <= 0.0:
        return Quat()

    # Convert to pyquaternion.quaternion.Quaternion and do operation:
    py_quat = Quaternion(rotation.get_w(),
        rotation.get_x(), rotation.get_y(), rotation.get_z())
    py_quat = py_quat ** progress

    # Compute back to panda3d.core.Quat:
    qresult = Quat()
    qresult.set_w(py_quat[0])
    qresult.set_x(py_quat[1])
    qresult.set_y(py_quat[2])
    qresult.set_z(py_quat[3])
    assert(not qresult.is_nan()),\
        "partial_rotation (" + str(rotation) +\
        " ** " + str(progress) + ") " +\
        "gave us NaN quaternion: " + str(qresult)
    return qresult
```
I always run into this error:
```
AssertionError: partial_rotation (-5.73123 + 0i + 0j + -8.78293k ** nan) gave us NaN quaternion: -nan + -nani + -nanj + -nank
```
